package com.example.MyBarServer.Repository

import com.example.MyBarServer.Models.Category
import com.example.MyBarServer.Models.Cocktail
import com.example.MyBarServer.Models.Glass
import com.example.MyBarServer.Models.Ingredient
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.stereotype.Repository
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource
import org.springframework.jdbc.support.GeneratedKeyHolder


@Repository
class CocktailRepository(@Autowired var namedParameterJdbcTemplate: NamedParameterJdbcTemplate) {

    final val INSERT_COCKTAIL_SQL = "INSERT INTO COCKTAIL_DB.COCKTAIL (name,description,glass,category,alcoholic,img_link) VALUES (:name,:description,:glass,:category, :alcoholic, :image_link) "

    fun addCocktail(cocktail: Cocktail): Int {

        //holds IDs generated by mysql:
        val keyHolder: GeneratedKeyHolder = GeneratedKeyHolder()

        val namedParameters = MapSqlParameterSource(hashMapOf(
                "image_link" to cocktail.image_link,
                "alcoholic" to cocktail.alcoholic,
                "category" to cocktail.category.name,
                "name" to cocktail.name,
                "description" to cocktail.description,
                "glass" to cocktail.glass.toString())
        )

        namedParameterJdbcTemplate.update(INSERT_COCKTAIL_SQL, namedParameters, keyHolder)

        return keyHolder.key!!.toInt()
    }

    val GET_COCKTAIL_SQL = "SELECT COCKTAIL.NAME  AS COCKTAILNAME,DESCRIPTION,GLASS,CATEGORY,INGREDIENT.NAME AS INGREDIENTNAME, AMOUNT FROM COCKTAIL JOIN COCKTAILHASINGREDIENT ON COCKTAIL.ID=COCKTAILHASINGREDIENT.COCKTAIL_ID JOIN INGREDIENT ON COCKTAILHASINGREDIENT.INGREDIENT_ID=INGREDIENT.ID WHERE COCKTAIL.ID=:cocktailid"


    fun getCocktail(id: Int): Cocktail {
        val namedParameters = MapSqlParameterSource(hashMapOf(
                "cocktailid" to id
        ))
        val res = namedParameterJdbcTemplate.queryForList(GET_COCKTAIL_SQL, namedParameters)

        /*val ingredients = hashMapOf<Ingredient,String>()
        for(row in res){
            ingredients.put(Ingredient(row.get("ingredientname").toString()), row.get("amount").toString())
        }
        */

        val ingredients = res.map { Ingredient(it.get("ingredientname").toString())}
        val amounts = res.map { it.get("amount").toString() }

        val row = res.get(0)

        //return Cocktail(Glass.valueOf(row.get("glass").toString()), row.get("cocktailname").toString(), ingredients, row.get("description").toString())
        return Cocktail(row.get("cocktailname").toString(),Glass.valueOf(row.get("glass").toString()), Category( row.get("category").toString()), ingredients, amounts, row.get("description").toString())
    }

    val LOG = LoggerFactory.getLogger(CocktailRepository::class.java)

    //Todo optimize:
    fun getCocktails(ids: List<Int>) : List<Cocktail> {
        val res = emptyList<Cocktail>().toMutableList()
        for(id in ids){
            res.add(getCocktail(id))
        }
        return res
    }

    //extremely shitty:

    val shittysql = "SELECT ID FROM COCKTAIL_DB.COCKTAIL"
    fun getAll() : List<Cocktail>{

        val ids = namedParameterJdbcTemplate.queryForList(shittysql, MapSqlParameterSource()).map { it.get("id").toString().toInt() }

        return getCocktails(ids)
    }
}