INSERT INTO COCKTAIL (name,description,glass) VALUES('Cocktail one with whisky', 'Cocktaildescription','HIGHBALL');
INSERT INTO COCKTAIL (name,description,glass) VALUES('Cocktail two with rum', 'Cocktaildescription','HIGHBALL');

INSERT INTO INGREDIENT (name) VALUES('WHISKY');
INSERT INTO INGREDIENT (name) VALUES('RUM');
INSERT INTO INGREDIENT (name) VALUES('LEMON');

INSERT INTO COCKTAILHASINGREDIENT VALUES (1,1,'4CL');
INSERT INTO COCKTAILHASINGREDIENT VALUES (1,3,'2CL');
INSERT INTO COCKTAILHASINGREDIENT VALUES (2,2,'4CL');
INSERT INTO COCKTAILHASINGREDIENT VALUES (2,3,'4CL');
